all:
  children:
    docker:
      hosts:
        35.246.125.65:
    manager:
      hosts:      
        34.89.59.203:
    worker:
      hosts:
        35.230.128.115:
    nginx:
      hosts:
        35.246.116.70:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: d_walker0357
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'