all:
  children:
    docker:
      hosts:
        10.154.0.8:
    manager:
      hosts:      
        10.154.0.12:
    worker:
      hosts:
        10.154.0.10:
    nginx:
      hosts:
        10.154.0.9:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'